### ISSUE TITLE
Make installation of npm-confirm modules opt-in rather than decide-again-and-again

### ISSUE THREAD

**Issue by J5lx** [kylekatarnls/nodejs-php-fallback#11]
As someone who does not use this package directly, I find it rather annoying that every single time I run composer update I have to answer for 11 different NPM packages that I don’t want to install them just because some of my PHP dependencies can *optionally* use them, since all of these packages serve to enable functionality that I don’t want anyway. I don’t consider --no-interaction a solution since it achieves the opposite of what I want (installing all suggested packages rather than none) and makes each invocation of composer take about twice as long as it usually would. Instead, I believe it would be much better if this package handled suggested Node packages the same way composer handles suggested PHP packages, i.e. by displaying a notice at the end of the installation output, like this after setting up a new laravel project:

> symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
> symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
> symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
> symfony/routing suggests installing symfony/expression-language (For using expression matching)
> symfony/routing suggests installing symfony/yaml (For using the YAML loader)
> paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
> symfony/event-dispatcher suggests installing symfony/dependency-injection ()
> symfony/http-kernel suggests installing symfony/browser-kit ()
> symfony/http-kernel suggests installing symfony/config ()
> symfony/http-kernel suggests installing symfony/dependency-injection ()
> symfony/console suggests installing symfony/lock ()
> ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
> ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
> ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
> ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
> ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
> ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
> symfony/translation suggests installing symfony/config ()
> symfony/translation suggests installing symfony/yaml ()
> monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
> monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
> monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
> monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
> monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
> monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
> monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
> monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
> monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
> monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
> monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
> league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
> league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
> league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
> league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
> league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
> league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
> league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
> league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
> league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
> league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
> league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
> laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
> laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.6).)
> laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~6.0).)
> laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
> laravel/framework suggests installing league/flysystem-cached-adapter (Required to use Flysystem caching (~1.0).)
> laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
> laravel/framework suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (~1.0).)
> laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
> laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
> laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
> laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~3.0).)
> laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (~4.0).)
> laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (~1.0).)
> psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
> psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
> filp/whoops suggests installing whoops/soap (Formats errors as SOAP responses)
> sebastian/global-state suggests installing ext-uopz (*)
> phpunit/phpunit suggests installing phpunit/php-invoker (^2.0)

The user could then decide to add the respective package(s) to the npm section in their own composer.json to actually install those suggested NPM packages, and they wouldn’t have to spend precious time of life on answering the same questions over and over whenever they update, add or remove dependencies. How about it?

**Comment by kylekatarnls** [comment]
In fact `--no-interaction` make the install of packages (as if you typed `Y`). So if you want to install and keep npm dependencies up to date, you can safely use `--no-interaction`.

**[EDIT]**

In the next version we will first ask the user for install (or not) all node packages and remember the choice or fallback to manually install each dependency.

**Comment by kylekatarnls** [comment]
Since 1.4.0, the choice can be remembered.
