### ISSUE TITLE
Plugin installation failed, rolling back

### ISSUE THREAD

**Issue by Mirocow** [kylekatarnls/nodejs-php-fallback#12]
- Installing yiisoft/yii2-composer (2.0.7): Loading from cache
  - Installing nodejs-php-fallback/nodejs-php-fallback (1.4.1): Loading from cache
Plugin installation failed, rolling back
  - Removing nodejs-php-fallback/nodejs-php-fallback (1.4.1)

  [RuntimeException]
  Could not delete /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback:

**Comment by Mirocow** [comment]
cd /app && composer require "pug-php/pug" "3.1.0"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 17 installs, 0 updates, 0 removals
  - Installing nodejs-php-fallback/nodejs-php-fallback (1.4.1): Loading from cache
Plugin installation failed, rolling back
  - Removing nodejs-php-fallback/nodejs-php-fallback (1.4.1)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not delete /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback:

**Comment by kylekatarnls** [comment]
Hi, to install Pug-php in Yii2, please use the dedicated adapter:

```shell
composer require pug/yii2
```

I tried both the command above and `composer require "pug-php/pug" "3.1.0"` in a yiisoft/yii2-composer app but I did not reproduce your error. I get successful installations for both.

Please give me `require` and `require-dev` entries of you **composer.json** and your PHP version.

PS: note than Pug-php 3.1.0 is very old and future changes made on Phug (the internal engine) are tested on last ^2 and ^3, so you should rather use "^3.2.0".

**Comment by kylekatarnls** [comment]
The `Could not delete` exception can be the sign:
- If you're on Windows: a process is locking the files (kill running PHP processes)
- If you're on Linux/Mac: the last install have been done with a different user, so the CHMOD does not allow you to delete the node_modules directory inside nodejs-php-fallback.

**Comment by Mirocow** [comment]
$ php -v
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

```bash
$ composer require nodejs-php-fallback/nodejs-php-fallback
XDebug could not open the remote debug file '/var/log/php7-fpm/php-fpm-xdebug-remote'.
Using version ^1.4 for nodejs-php-fallback/nodejs-php-fallback
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing nodejs-php-fallback/nodejs-php-fallback (1.4.1): Loading from cache
Plugin installation failed, rolling back
  - Removing nodejs-php-fallback/nodejs-php-fallback (1.4.1)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not delete /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback:
```

```bash
$ composer require pug/yii2
XDebug could not open the remote debug file '/var/log/php7-fpm/php-fpm-xdebug-remote'.
Using version ^1.1 for pug/yii2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 19 installs, 0 updates, 0 removals
  - Installing nodejs-php-fallback/nodejs-php-fallback (1.4.1): Loading from cache
Plugin installation failed, rolling back
  - Removing nodejs-php-fallback/nodejs-php-fallback (1.4.1)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not delete /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback:
```

```bash
$ composer require "pug-php/pug" "3.2.0"
XDebug could not open the remote debug file '/var/log/php7-fpm/php-fpm-xdebug-remote'.
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 18 installs, 0 updates, 0 removals
  - Installing nodejs-php-fallback/nodejs-php-fallback (1.4.1): Loading from cache
Plugin installation failed, rolling back
  - Removing nodejs-php-fallback/nodejs-php-fallback (1.4.1)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not delete /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback:
```

**Comment by kylekatarnls** [comment]
Did you check my second comment: https://github.com/kylekatarnls/nodejs-php-fallback/issues/12#issuecomment-493355638

As same steps work on my machine, my assumption is there is a file locked/not writable for your current user inside `/app/vendor/nodejs-php-fallback`. If so, there is nothing we can do from the library side, try to remove it manually first: `rm /app/vendor/nodejs-php-fallback`

If it failed, so composer could neither remove it. You need then to user a sudoer user or the one that own/created `/app/vendor/nodejs-php-fallback` in the first place to remove it.

I see you use FPM, I believe, it also can change rights/owner of files it creates.

**Comment by Mirocow** [comment]
```
vagrant@y2aa:/app$ ls -la  /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/
total 0
drwxrwxrwx 1 vagrant vagrant  96 Apr  5  2018 .
drwxrwxrwx 1 vagrant vagrant  96 May 17 14:04 ..
drwxrwxrwx 1 vagrant vagrant 192 Apr  5  2018 NodejsPhpFallback

```

```
vagrant@y2aa:/app$ ls -la  /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback/
total 24
drwxrwxrwx 1 vagrant vagrant  192 Apr  5  2018 .
drwxrwxrwx 1 vagrant vagrant   96 Apr  5  2018 ..
-rw-rw-rw- 1 vagrant vagrant  713 Apr  5  2018 ComposerPlugin.php
-rw-rw-rw- 1 vagrant vagrant 9605 Apr  5  2018 NodejsPhpFallback.php
-rw-rw-rw- 1 vagrant vagrant  132 Apr  5  2018 WrapperInterface.php
-rw-rw-rw- 1 vagrant vagrant 1543 Apr  5  2018 Wrapper.php
```

```
Dependency resolution completed in 0.001 seconds
Package operations: 1 install, 0 updates, 0 removals
Installs: nodejs-php-fallback/nodejs-php-fallback:1.4.0
  - Installing nodejs-php-fallback/nodejs-php-fallback (1.4.0): Reading /home/vagrant/.cache/composer/files/nodejs-php-fallback/nodejs-php-fallback/aba4de2bf457420e87d5f03a0d11b5b0a05df209.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/app/vendor/nodejs-php-fallback/nodejs-php-fallback/3b40550ee97c9a3509395f4b69cfc8ac' -d '/app/vendor/composer/707b4c34'
Plugin installation failed, rolling back
  - Removing nodejs-php-fallback/nodejs-php-fallback (1.4.0)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not delete /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback
```

if vendor folder is clean and start composer install the error same

**Comment by kylekatarnls** [comment]
> Please give me require and require-dev entries of you composer.json

Then can you try for debug purpose: `composer require pug/yii2 --no-scripts`

**Comment by Mirocow** [comment]
```
vagrant@y2aa:/app$ rm -R /app/vendor/nodejs-php-fallback/nodejs-php-fallback/*
vagrant@y2aa:/app$ ls -la /app/vendor/nodejs-php-fallback/nodejs-php-fallback/
total 0
drwxrwxrwx 1 vagrant vagrant 64 May 17 15:34 .
drwxrwxrwx 1 vagrant vagrant 96 May 17 13:49 ..

vagrant@y2aa:/app$ composer require pug/yii2 --no-scripts
XDebug could not open the remote debug file '/var/log/php7-fpm/php-fpm-xdebug-remote'.
Using version ^1.1 for pug/yii2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 19 installs, 0 updates, 0 removals
  - Installing nodejs-php-fallback/nodejs-php-fallback (1.4.1): Loading from cache
Plugin installation failed, rolling back
  - Removing nodejs-php-fallback/nodejs-php-fallback (1.4.1)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not delete /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback:
```

With debug

```
Dependency resolution completed in 0.001 seconds
Package operations: 19 installs, 0 updates, 0 removals
Installs: nodejs-php-fallback/nodejs-php-fallback:1.4.1, js-transformer/js-transformer:1.0.0, symfony/var-dumper:v3.4.27, phug/event:0.1.2, phug/util:0.4.16, phug/ast:0.1.0, phug/reader:0.2.2, phug/lexer:0.5.34, phug/parser:0.5.8, phug/dependency-injection:1.3.2, phug/formatter:0.5.48, phug/compiler:0.5.24, phug/renderer:0.4.8, phug/phug:0.3.2, phug/js-transformer-filter:1.1.0, js-phpize/js-phpize:2.4.0, js-phpize/js-phpize-phug:2.1.0, pug-php/pug:3.2.0, pug/yii2:1.1.0
  - Installing nodejs-php-fallback/nodejs-php-fallback (1.4.1): Reading /home/vagrant/.cache/composer/files/nodejs-php-fallback/nodejs-php-fallback/0519240ef96c93040b7b03912db8eaef2c7d42ba.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/app/vendor/nodejs-php-fallback/nodejs-php-fallback/c0fdfd4a783b8612d9e7c2ee3830dec5' -d '/app/vendor/composer/a48fc3d2'
Plugin installation failed, rolling back
  - Removing nodejs-php-fallback/nodejs-php-fallback (1.4.1)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not delete /app/vendor/nodejs-php-fallback/nodejs-php-fallback/src/NodejsPhpFallback
```

**Comment by kylekatarnls** [comment]
Sadly, when disabling scripts `--no-scripts`, nodejs-php-fallback is just 4 simple PHP files to copy. So this is certainly not a problem related to our package, but more likely something composer is not compatible with or something wrong in your other dependencies, as you don't share your require/require-dev settings, I can't guess more than that.

What about trying to require an other random package for comparison?

**Comment by Mirocow** [comment]
please update https://packagist.org
when i added gitub repo, my problem resolved

```
        {
            "type": "git",
            "url": "https://github.com/kylekatarnls/nodejs-php-fallback.git"
        }
```

        "nodejs-php-fallback/nodejs-php-fallback": "1.4.1",
        "pug-php/pug": "@dev"

**Comment by kylekatarnls** [comment]
Packagist is yet up to date: 1.4.1 as last release and dev-master is 94f5743cc0a0344af84892b1ad49a62f06d06756 (the last commit on GitHub).

So there is nothing wrong with the package: composer bug or something in your machine or other dependencies. It seem to fail after `unzip -qq` and when you use directly the git repository, this command is not triggered. Maybe you should check unzip works correctly on your machine.
