### ISSUE TITLE
Fallback to support php-7.1 and php-7.2 versions

### ISSUE THREAD

**Issue by peter279k** [kylekatarnls/nodejs-php-fallback#21]
As title, it seems that this PHP package requires `php-7.3` version at least on `master` branch.

The `php-7.1` and `php-7.2` versions are active and I think we should support `php-7.1` version at least.

**Comment by kylekatarnls** [comment]
They are officially no longer in active support for the PHP team:
https://www.php.net/supported-versions.php

This small util is stable enough (very few bugs/features request) so PHP users from 5.3 to 7.2 can use 1.x versions with pretty equivalent features.

Here is why I did a bigger jump for the version 2 of this package.

**Comment by peter279k** [comment]
Thanks for your reply, @kylekatarnls.

Should we release new version for this package?

**Comment by kylekatarnls** [comment]
No need until there actually is a new feature/fix/optimization. The drop of old PHP versions can be helpful for contributors of the project, but it brings nothing more to users.
