### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by narirou** [kylekatarnls/nodejs-php-fallback#9]
Hello.
We are trying to use the `php-pug` package in a production environment.
So, I want to know the license of this package which depends on `php-pug`.

Thanks.

**Comment by kylekatarnls** [comment]
Hi sorry, I thought it already was added. nodejs-php-fallback is under MIT license.

Know that, if you `"pugjs" => true` option, nodejs-php-fallback is not called.

**Comment by narirou** [comment]
Thank you! 👍
